FROM alpine as build

# Update and install deps

RUN apk update --no-cache

RUN apk add --no-cache \
    ca-certificates \
    wget \
    zip \
    build-base \
    bash \
    cmake

WORKDIR /tmp

ADD bin bin
ADD patches/alpine patches

RUN ./bin/download_ssc.sh
RUN cp -R patches/* .
RUN ./bin/build_ssc.sh
RUN ./bin/install_ssc.sh

FROM alpine

COPY --from=build /usr/lib/libssc.so /usr/local/lib/libssc.so
COPY --from=build /usr/include/sscapi.h /usr/local/include/sscapi.h
